#!/bin/bash
# First-time setup for Claude Dev Container
# Detects host environment and generates .env for docker-compose
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Claude Dev Container Setup${NC}"
echo ""

# Detect host home directory
HOST_HOME="$HOME"
HOST_USER="$(whoami)"
REPOS_DIR="$(dirname "$SCRIPT_DIR")"

# Detect total memory (in GB) for container limits
if [[ "$(uname)" == "Darwin" ]]; then
    TOTAL_MEM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
else
    TOTAL_MEM_GB=$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1048576 ))
fi
# Reserve 4GB for host OS, minimum 4GB for container
CONTAINER_MEM_GB=$(( TOTAL_MEM_GB - 4 ))
if [ "$CONTAINER_MEM_GB" -lt 4 ]; then
    CONTAINER_MEM_GB=4
fi

# Platform-specific defaults
DOCKER_SOCK="/var/run/docker.sock"
MACHINE_ID_MOUNT=""
X11_MOUNT=""

if [[ "$(uname)" == "Darwin" ]]; then
    # macOS: Docker Desktop socket location
    if [ -e "$HOME/.docker/run/docker.sock" ]; then
        DOCKER_SOCK="$HOME/.docker/run/docker.sock"
    fi
    # No machine-id or X11 on macOS
else
    # Linux: mount machine-id and X11
    MACHINE_ID_MOUNT="/etc/machine-id:/etc/machine-id:ro"
    X11_MOUNT="/tmp/.X11-unix:/tmp/.X11-unix:ro"
fi

# Check for existing .env
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Existing .env found. Overwrite? (y/n)${NC}"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env"
        exit 0
    fi
fi

# Write .env
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — do not commit this file
# Re-run ./setup.sh to regenerate

# Host paths (detected automatically)
HOST_HOME=$HOST_HOME
HOST_USER=$HOST_USER
REPOS_DIR=$REPOS_DIR

# Container resource limits
CONTAINER_MEM=${CONTAINER_MEM_GB}g

# Platform-specific mounts (empty string = skip)
DOCKER_SOCK=$DOCKER_SOCK
MACHINE_ID_MOUNT=$MACHINE_ID_MOUNT
X11_MOUNT=$X11_MOUNT

# Timezone
TZ=${TZ:-America/Los_Angeles}
EOF

echo -e "${GREEN}Generated .env:${NC}"
echo "  HOST_HOME=$HOST_HOME"
echo "  REPOS_DIR=$REPOS_DIR"
echo "  CONTAINER_MEM=${CONTAINER_MEM_GB}g"
echo "  DOCKER_SOCK=$DOCKER_SOCK"
echo ""

# Check for Telegram bot token
TELEGRAM_ENV="$SCRIPT_DIR/telegram-bot/.env"
if [ -f "$TELEGRAM_ENV" ]; then
    echo -e "${GREEN}Telegram bot token found${NC}"
else
    echo -e "${YELLOW}No telegram-bot/.env found — TinyClaw Telegram channel will be disabled${NC}"
    echo "  Create $TELEGRAM_ENV with TELEGRAM_BOT_TOKEN=<token> to enable"
fi

# Generate workspace CLAUDE.md with machine-specific paths
CLAUDE_MD="$REPOS_DIR/CLAUDE.md"
cat > "$CLAUDE_MD" <<EOF
# Workspace: $REPOS_DIR

## Environment

- You are inside a devcontainer. Your HOME is \`$HOST_HOME\` (NOT \`/home/node\`).
- Never write files to \`/home/node\` — it is not volume-mounted to the host.

## File Sharing Between Projects

- **Shared directory:** \`$REPOS_DIR/.shared/\` — use this for any files that need to be visible to other agents, projects, or the user (plans, specs, data exports, etc.)
  - Plans and specs: \`$REPOS_DIR/.shared/plans/\`
- **Project files** stay in their project directory: \`$REPOS_DIR/<project>/\`
- When referencing files for another person or agent, always use absolute paths under \`$REPOS_DIR/\`
EOF

# Create shared directories
mkdir -p "$REPOS_DIR/.shared/plans"

# Ensure agent config dirs exist on host before docker-compose mounts them
# (otherwise docker auto-creates them as root-owned)
mkdir -p "$HOST_HOME/.claude" "$HOST_HOME/.codex"

echo -e "${GREEN}Generated CLAUDE.md at $CLAUDE_MD${NC}"
echo ""
echo -e "${GREEN}Setup complete.${NC} Next steps:"
echo "  1. source aliases.sh    # Add to ~/.bashrc or ~/.zshrc"
echo "  2. claude-build         # Build the container"
echo "  3. claude-up            # Start the container"
echo "  4. cs <project>         # Start a session"
